services:
  wholby-proxy:
    build: .
    container_name: wholby-proxy
    restart: unless-stopped
    ports:
      - "8096:8096"
    env_file:
      - .env
    # Optional: If running on the same machine as Emby, 
    # setting network_mode to host can resolve routing issues.
    # network_mode: "host"
